from dataclasses import dataclass, field
from typing import Any, Mapping

from ._coerce import to_float, to_int, to_int_list

@dataclass(slots=True, frozen=True)
class ChallengesDto:
    twelveAssistStreakCount: int = 0
    baronBuffGoldAdvantageOverThreshold: int = 0
    controlWardTimeCoverageInRiverOrEnemyHalf: float = 0.0
    earliestBaron: int = 0
    earliestDragonTakedown: int = 0
    earliestElderDragon: int = 0
    earlyLaningPhaseGoldExpAdvantage: int = 0
    fasterSupportQuestCompletion: int = 0
    fastestLegendary: int = 0
    hadAfkTeammate: int = 0
    highestChampionDamage: int = 0
    highestCrowdControlScore: int = 0
    highestWardKills: int = 0
    junglerKillsEarlyJungle: int = 0
    killsOnLanersEarlyJungleAsJungler: int = 0
    laningPhaseGoldExpAdvantage: int = 0
    legendaryCount: int = 0
    maxCsAdvantageOnLaneOpponent: float = 0.0
    maxLevelLeadLaneOpponent: int = 0
    mostWardsDestroyedOneSweeper: int = 0
    mythicItemUsed: int = 0
    playedChampSelectPosition: int = 0
    soloTurretsLategame: int = 0
    takedownsFirst25Minutes: int = 0
    teleportTakedowns: int = 0
    thirdInhibitorDestroyedTime: int = 0
    threeWardsOneSweeperCount: int = 0
    visionScoreAdvantageLaneOpponent: float = 0.0
    InfernalScalePickup: int = 0
    fistBumpParticipation: int = 0
    voidMonsterKill: int = 0
    abilityUses: int = 0
    acesBefore15Minutes: int = 0
    alliedJungleMonsterKills: float = 0.0
    baronTakedowns: int = 0
    blastConeOppositeOpponentCount: int = 0
    bountyGold: int = 0
    buffsStolen: int = 0
    completeSupportQuestInTime: int = 0
    controlWardsPlaced: int = 0
    damagePerMinute: float = 0.0
    damageTakenOnTeamPercentage: float = 0.0
    dancedWithRiftHerald: int = 0
    deathsByEnemyChamps: int = 0
    dodgeSkillShotsSmallWindow: int = 0
    doubleAces: int = 0
    dragonTakedowns: int = 0
    legendaryItemUsed: list[int] = field(default_factory=list)
    effectiveHealAndShielding: float = 0.0
    elderDragonKillsWithOpposingSoul: int = 0
    elderDragonMultikills: int = 0
    enemyChampionImmobilizations: int = 0
    enemyJungleMonsterKills: float = 0.0
    epicMonsterKillsNearEnemyJungler: int = 0
    epicMonsterKillsWithin30SecondsOfSpawn: int = 0
    epicMonsterSteals: int = 0
    epicMonsterStolenWithoutSmite: int = 0
    firstTurretKilled: int = 0
    firstTurretKilledTime: float = 0.0
    flawlessAces: int = 0
    fullTeamTakedown: int = 0
    gameLength: float = 0.0
    getTakedownsInAllLanesEarlyJungleAsLaner: int = 0
    goldPerMinute: float = 0.0
    hadOpenNexus: int = 0
    immobilizeAndKillWithAlly: int = 0
    initialBuffCount: int = 0
    initialCrabCount: int = 0
    jungleCsBefore10Minutes: float = 0.0
    junglerTakedownsNearDamagedEpicMonster: int = 0
    kda: float = 0.0
    killAfterHiddenWithAlly: int = 0
    killedChampTookFullTeamDamageSurvived: int = 0
    killingSprees: int = 0
    killParticipation: float = 0.0
    killsNearEnemyTurret: int = 0
    killsOnOtherLanesEarlyJungleAsLaner: int = 0
    killsOnRecentlyHealedByAramPack: int = 0
    killsUnderOwnTurret: int = 0
    killsWithHelpFromEpicMonster: int = 0
    knockEnemyIntoTeamAndKill: int = 0
    kTurretsDestroyedBeforePlatesFall: int = 0
    landSkillShotsEarlyGame: int = 0
    laneMinionsFirst10Minutes: int = 0
    lostAnInhibitor: int = 0
    maxKillDeficit: int = 0
    mejaisFullStackInTime: int = 0
    moreEnemyJungleThanOpponent: float = 0.0
    multiKillOneSpell: int = 0
    """This is an offshoot of the OneStone challenge. The code checks if a spell with the same instance ID does the final point of damage to at least 2 Champions. It doesn't matter if they're enemies, but you cannot hurt your friends."""
    multikills: int = 0
    multikillsAfterAggressiveFlash: int = 0
    multiTurretRiftHeraldCount: int = 0
    outerTurretExecutesBefore10Minutes: int = 0
    outnumberedKills: int = 0
    outnumberedNexusKill: int = 0
    perfectDragonSoulsTaken: int = 0
    perfectGame: int = 0
    pickKillWithAlly: int = 0
    poroExplosions: int = 0
    quickCleanse: int = 0
    quickFirstTurret: int = 0
    quickSoloKills: int = 0
    riftHeraldTakedowns: int = 0
    saveAllyFromDeath: int = 0
    scuttleCrabKills: int = 0
    shortestTimeToAceFromFirstTakedown: float = 0.0
    skillshotsDodged: int = 0
    skillshotsHit: int = 0
    snowballsHit: int = 0
    soloBaronKills: int = 0
    SWARM_DefeatAatrox: int = 0
    SWARM_DefeatBriar: int = 0
    SWARM_DefeatMiniBosses: int = 0
    SWARM_EvolveWeapon: int = 0
    SWARM_Have3Passives: int = 0
    SWARM_KillEnemy: int = 0
    SWARM_PickupGold: float = 0.0
    SWARM_ReachLevel50: int = 0
    SWARM_Survive15Min: int = 0
    SWARM_WinWith5EvolvedWeapons: int = 0
    soloKills: int = 0
    stealthWardsPlaced: int = 0
    survivedSingleDigitHpCount: int = 0
    survivedThreeImmobilizesInFight: int = 0
    takedownOnFirstTurret: int = 0
    takedowns: int = 0
    takedownsAfterGainingLevelAdvantage: int = 0
    takedownsBeforeJungleMinionSpawn: int = 0
    takedownsFirstXMinutes: int = 0
    takedownsInAlcove: int = 0
    takedownsInEnemyFountain: int = 0
    teamBaronKills: int = 0
    teamDamagePercentage: float = 0.0
    teamElderDragonKills: int = 0
    teamRiftHeraldKills: int = 0
    tookLargeDamageSurvived: int = 0
    turretPlatesTaken: int = 0
    turretsTakenWithRiftHerald: int = 0
    """Any player who damages a tower that is destroyed within 30 seconds of a Rift Herald charge will receive credit. A player who does not damage the tower will not receive credit."""
    turretTakedowns: int = 0
    twentyMinionsIn3SecondsCount: int = 0
    twoWardsOneSweeperCount: int = 0
    unseenRecalls: int = 0
    visionScorePerMinute: float = 0.0
    wardsGuarded: int = 0
    wardTakedowns: int = 0
    wardTakedownsBefore20M: int = 0

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "ChallengesDto":
        payload = dict(data or {})
        return cls(
            twelveAssistStreakCount=to_int(payload.get("12AssistStreakCount")),
            baronBuffGoldAdvantageOverThreshold=to_int(payload.get("baronBuffGoldAdvantageOverThreshold")),
            controlWardTimeCoverageInRiverOrEnemyHalf=to_float(payload.get("controlWardTimeCoverageInRiverOrEnemyHalf")),
            earliestBaron=to_int(payload.get("earliestBaron")),
            earliestDragonTakedown=to_int(payload.get("earliestDragonTakedown")),
            earliestElderDragon=to_int(payload.get("earliestElderDragon")),
            earlyLaningPhaseGoldExpAdvantage=to_int(payload.get("earlyLaningPhaseGoldExpAdvantage")),
            fasterSupportQuestCompletion=to_int(payload.get("fasterSupportQuestCompletion")),
            fastestLegendary=to_int(payload.get("fastestLegendary")),
            hadAfkTeammate=to_int(payload.get("hadAfkTeammate")),
            highestChampionDamage=to_int(payload.get("highestChampionDamage")),
            highestCrowdControlScore=to_int(payload.get("highestCrowdControlScore")),
            highestWardKills=to_int(payload.get("highestWardKills")),
            junglerKillsEarlyJungle=to_int(payload.get("junglerKillsEarlyJungle")),
            killsOnLanersEarlyJungleAsJungler=to_int(payload.get("killsOnLanersEarlyJungleAsJungler")),
            laningPhaseGoldExpAdvantage=to_int(payload.get("laningPhaseGoldExpAdvantage")),
            legendaryCount=to_int(payload.get("legendaryCount")),
            maxCsAdvantageOnLaneOpponent=to_float(payload.get("maxCsAdvantageOnLaneOpponent")),
            maxLevelLeadLaneOpponent=to_int(payload.get("maxLevelLeadLaneOpponent")),
            mostWardsDestroyedOneSweeper=to_int(payload.get("mostWardsDestroyedOneSweeper")),
            mythicItemUsed=to_int(payload.get("mythicItemUsed")),
            playedChampSelectPosition=to_int(payload.get("playedChampSelectPosition")),
            soloTurretsLategame=to_int(payload.get("soloTurretsLategame")),
            takedownsFirst25Minutes=to_int(payload.get("takedownsFirst25Minutes")),
            teleportTakedowns=to_int(payload.get("teleportTakedowns")),
            thirdInhibitorDestroyedTime=to_int(payload.get("thirdInhibitorDestroyedTime")),
            threeWardsOneSweeperCount=to_int(payload.get("threeWardsOneSweeperCount")),
            visionScoreAdvantageLaneOpponent=to_float(payload.get("visionScoreAdvantageLaneOpponent")),
            InfernalScalePickup=to_int(payload.get("InfernalScalePickup")),
            fistBumpParticipation=to_int(payload.get("fistBumpParticipation")),
            voidMonsterKill=to_int(payload.get("voidMonsterKill")),
            abilityUses=to_int(payload.get("abilityUses")),
            acesBefore15Minutes=to_int(payload.get("acesBefore15Minutes")),
            alliedJungleMonsterKills=to_float(payload.get("alliedJungleMonsterKills")),
            baronTakedowns=to_int(payload.get("baronTakedowns")),
            blastConeOppositeOpponentCount=to_int(payload.get("blastConeOppositeOpponentCount")),
            bountyGold=to_int(payload.get("bountyGold")),
            buffsStolen=to_int(payload.get("buffsStolen")),
            completeSupportQuestInTime=to_int(payload.get("completeSupportQuestInTime")),
            controlWardsPlaced=to_int(payload.get("controlWardsPlaced")),
            damagePerMinute=to_float(payload.get("damagePerMinute")),
            damageTakenOnTeamPercentage=to_float(payload.get("damageTakenOnTeamPercentage")),
            dancedWithRiftHerald=to_int(payload.get("dancedWithRiftHerald")),
            deathsByEnemyChamps=to_int(payload.get("deathsByEnemyChamps")),
            dodgeSkillShotsSmallWindow=to_int(payload.get("dodgeSkillShotsSmallWindow")),
            doubleAces=to_int(payload.get("doubleAces")),
            dragonTakedowns=to_int(payload.get("dragonTakedowns")),
            legendaryItemUsed=to_int_list(payload.get("legendaryItemUsed")),
            effectiveHealAndShielding=to_float(payload.get("effectiveHealAndShielding")),
            elderDragonKillsWithOpposingSoul=to_int(payload.get("elderDragonKillsWithOpposingSoul")),
            elderDragonMultikills=to_int(payload.get("elderDragonMultikills")),
            enemyChampionImmobilizations=to_int(payload.get("enemyChampionImmobilizations")),
            enemyJungleMonsterKills=to_float(payload.get("enemyJungleMonsterKills")),
            epicMonsterKillsNearEnemyJungler=to_int(payload.get("epicMonsterKillsNearEnemyJungler")),
            epicMonsterKillsWithin30SecondsOfSpawn=to_int(payload.get("epicMonsterKillsWithin30SecondsOfSpawn")),
            epicMonsterSteals=to_int(payload.get("epicMonsterSteals")),
            epicMonsterStolenWithoutSmite=to_int(payload.get("epicMonsterStolenWithoutSmite")),
            firstTurretKilled=to_int(payload.get("firstTurretKilled")),
            firstTurretKilledTime=to_float(payload.get("firstTurretKilledTime")),
            flawlessAces=to_int(payload.get("flawlessAces")),
            fullTeamTakedown=to_int(payload.get("fullTeamTakedown")),
            gameLength=to_float(payload.get("gameLength")),
            getTakedownsInAllLanesEarlyJungleAsLaner=to_int(payload.get("getTakedownsInAllLanesEarlyJungleAsLaner")),
            goldPerMinute=to_float(payload.get("goldPerMinute")),
            hadOpenNexus=to_int(payload.get("hadOpenNexus")),
            immobilizeAndKillWithAlly=to_int(payload.get("immobilizeAndKillWithAlly")),
            initialBuffCount=to_int(payload.get("initialBuffCount")),
            initialCrabCount=to_int(payload.get("initialCrabCount")),
            jungleCsBefore10Minutes=to_float(payload.get("jungleCsBefore10Minutes")),
            junglerTakedownsNearDamagedEpicMonster=to_int(payload.get("junglerTakedownsNearDamagedEpicMonster")),
            kda=to_float(payload.get("kda")),
            killAfterHiddenWithAlly=to_int(payload.get("killAfterHiddenWithAlly")),
            killedChampTookFullTeamDamageSurvived=to_int(payload.get("killedChampTookFullTeamDamageSurvived")),
            killingSprees=to_int(payload.get("killingSprees")),
            killParticipation=to_float(payload.get("killParticipation")),
            killsNearEnemyTurret=to_int(payload.get("killsNearEnemyTurret")),
            killsOnOtherLanesEarlyJungleAsLaner=to_int(payload.get("killsOnOtherLanesEarlyJungleAsLaner")),
            killsOnRecentlyHealedByAramPack=to_int(payload.get("killsOnRecentlyHealedByAramPack")),
            killsUnderOwnTurret=to_int(payload.get("killsUnderOwnTurret")),
            killsWithHelpFromEpicMonster=to_int(payload.get("killsWithHelpFromEpicMonster")),
            knockEnemyIntoTeamAndKill=to_int(payload.get("knockEnemyIntoTeamAndKill")),
            kTurretsDestroyedBeforePlatesFall=to_int(payload.get("kTurretsDestroyedBeforePlatesFall")),
            landSkillShotsEarlyGame=to_int(payload.get("landSkillShotsEarlyGame")),
            laneMinionsFirst10Minutes=to_int(payload.get("laneMinionsFirst10Minutes")),
            lostAnInhibitor=to_int(payload.get("lostAnInhibitor")),
            maxKillDeficit=to_int(payload.get("maxKillDeficit")),
            mejaisFullStackInTime=to_int(payload.get("mejaisFullStackInTime")),
            moreEnemyJungleThanOpponent=to_float(payload.get("moreEnemyJungleThanOpponent")),
            multiKillOneSpell=to_int(payload.get("multiKillOneSpell")),
            multikills=to_int(payload.get("multikills")),
            multikillsAfterAggressiveFlash=to_int(payload.get("multikillsAfterAggressiveFlash")),
            multiTurretRiftHeraldCount=to_int(payload.get("multiTurretRiftHeraldCount")),
            outerTurretExecutesBefore10Minutes=to_int(payload.get("outerTurretExecutesBefore10Minutes")),
            outnumberedKills=to_int(payload.get("outnumberedKills")),
            outnumberedNexusKill=to_int(payload.get("outnumberedNexusKill")),
            perfectDragonSoulsTaken=to_int(payload.get("perfectDragonSoulsTaken")),
            perfectGame=to_int(payload.get("perfectGame")),
            pickKillWithAlly=to_int(payload.get("pickKillWithAlly")),
            poroExplosions=to_int(payload.get("poroExplosions")),
            quickCleanse=to_int(payload.get("quickCleanse")),
            quickFirstTurret=to_int(payload.get("quickFirstTurret")),
            quickSoloKills=to_int(payload.get("quickSoloKills")),
            riftHeraldTakedowns=to_int(payload.get("riftHeraldTakedowns")),
            saveAllyFromDeath=to_int(payload.get("saveAllyFromDeath")),
            scuttleCrabKills=to_int(payload.get("scuttleCrabKills")),
            shortestTimeToAceFromFirstTakedown=to_float(payload.get("shortestTimeToAceFromFirstTakedown")),
            skillshotsDodged=to_int(payload.get("skillshotsDodged")),
            skillshotsHit=to_int(payload.get("skillshotsHit")),
            snowballsHit=to_int(payload.get("snowballsHit")),
            soloBaronKills=to_int(payload.get("soloBaronKills")),
            SWARM_DefeatAatrox=to_int(payload.get("SWARM_DefeatAatrox")),
            SWARM_DefeatBriar=to_int(payload.get("SWARM_DefeatBriar")),
            SWARM_DefeatMiniBosses=to_int(payload.get("SWARM_DefeatMiniBosses")),
            SWARM_EvolveWeapon=to_int(payload.get("SWARM_EvolveWeapon")),
            SWARM_Have3Passives=to_int(payload.get("SWARM_Have3Passives")),
            SWARM_KillEnemy=to_int(payload.get("SWARM_KillEnemy")),
            SWARM_PickupGold=to_float(payload.get("SWARM_PickupGold")),
            SWARM_ReachLevel50=to_int(payload.get("SWARM_ReachLevel50")),
            SWARM_Survive15Min=to_int(payload.get("SWARM_Survive15Min")),
            SWARM_WinWith5EvolvedWeapons=to_int(payload.get("SWARM_WinWith5EvolvedWeapons")),
            soloKills=to_int(payload.get("soloKills")),
            stealthWardsPlaced=to_int(payload.get("stealthWardsPlaced")),
            survivedSingleDigitHpCount=to_int(payload.get("survivedSingleDigitHpCount")),
            survivedThreeImmobilizesInFight=to_int(payload.get("survivedThreeImmobilizesInFight")),
            takedownOnFirstTurret=to_int(payload.get("takedownOnFirstTurret")),
            takedowns=to_int(payload.get("takedowns")),
            takedownsAfterGainingLevelAdvantage=to_int(payload.get("takedownsAfterGainingLevelAdvantage")),
            takedownsBeforeJungleMinionSpawn=to_int(payload.get("takedownsBeforeJungleMinionSpawn")),
            takedownsFirstXMinutes=to_int(payload.get("takedownsFirstXMinutes")),
            takedownsInAlcove=to_int(payload.get("takedownsInAlcove")),
            takedownsInEnemyFountain=to_int(payload.get("takedownsInEnemyFountain")),
            teamBaronKills=to_int(payload.get("teamBaronKills")),
            teamDamagePercentage=to_float(payload.get("teamDamagePercentage")),
            teamElderDragonKills=to_int(payload.get("teamElderDragonKills")),
            teamRiftHeraldKills=to_int(payload.get("teamRiftHeraldKills")),
            tookLargeDamageSurvived=to_int(payload.get("tookLargeDamageSurvived")),
            turretPlatesTaken=to_int(payload.get("turretPlatesTaken")),
            turretsTakenWithRiftHerald=to_int(payload.get("turretsTakenWithRiftHerald")),
            turretTakedowns=to_int(payload.get("turretTakedowns")),
            twentyMinionsIn3SecondsCount=to_int(payload.get("twentyMinionsIn3SecondsCount")),
            twoWardsOneSweeperCount=to_int(payload.get("twoWardsOneSweeperCount")),
            unseenRecalls=to_int(payload.get("unseenRecalls")),
            visionScorePerMinute=to_float(payload.get("visionScorePerMinute")),
            wardsGuarded=to_int(payload.get("wardsGuarded")),
            wardTakedowns=to_int(payload.get("wardTakedowns")),
            wardTakedownsBefore20M=to_int(payload.get("wardTakedownsBefore20M")),
        )


